apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - type: helm
      url: https://registry.astechdemo.de/chartrepo/cncfcnsdeuprod
      name: cncfcnsdeuprod
      usernameSecret:
        name: harbor-docker-secret
        key: username
      passwordSecret:
        name: harbor-docker-secret
        key: password
