apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anirbansahademo/cnsecdayeu2021-example-app.git
    targetRevision: HEAD
    path: helm-app/

    helm:
      releaseName: example-app-deploy
      values: |
        app-deploy:
          image_tag: "0.0.1"

  destination:
    server: https://kubernetes.default.svc
    namespace: app-project

  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
