---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-docker-cm
  namespace: {{ .Release.Namespace }}
data:
  DOCKER_TAG: "{{ .Values.image_tag }}"
  DOCKER_IMAGE_NAME: {{ .Values.app_name }}
  DOCKER_TEST_NAMESPACE: {{ .Values.docker_registry_test_namespace }}
  DOCKER_PROD_NAMESPACE: {{ .Values.docker_registry_prod_namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-argocd-cm
  namespace: {{ .Release.Namespace }}
data:
  ARGOCD_SERVER: "{{ .Values.argocd_server }}"
  ARGOCD_APPLICATION_NAME: {{ .Values.app_name }}-deploy
