apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anirbansahademo/cnsecdayeu2021-example-app.git
    targetRevision: HEAD
    path: helm

    helm:
      releaseName: example-app
      valueFiles:
      - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: example-app

  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
